### ISSUE TITLE
Cut stable/ocata release

### ISSUE THREAD

**Issue by kornicameister** [monasca/monasca-docker#149]
The point of this issue is prepare the **stable/ocata** based **monasca-docker**. 
There are couple of activities that needs to be completed:

- [ ] make all images follow standard **monasca/python** #143 
- [ ] create tags for ocata release for all images #147 
- [ ] add foundation to be able to specify the version of images for ```docker-compose up``` run #145 
- [ ] make configuration templates compatible with each release 
- [ ] add stage to **CI** to run **stable/ocata**

**Comment by kornicameister** [comment]
@timothyb89 @mhoppal  - this is just placeholder I've added to keep a track over all activities that I believe we need to address / take to be able to run true **stable/ocata** docker-compose. 

For some of the points, there are already PRs, some needs to be still addressed. If you feel like that's not everything, just let me know. Also if any points feels off or it requires some more discussion - let's do that.

As I mentioned, a while ago, that's in our (Fujitsu) interest and I would really appreciate a help here :).

**Comment by timothyb89** [comment]
side note - sidecar is an optional component, you can disable (or even remove the patch from the image build entirely) without breaking anything, especially in a docker-only environment. Without additional configuration the metrics it gathers won't even be collected by the agent, since it's configured to use Kubernetes-only autodiscovery right now.

**Comment by kornicameister** [comment]
@timothyb89 guess we have all necessary bits in the images in place to proceed with cutting **stable** branch. Are you fine with us with creating **stable/ocata** for the start and figuring out all the backports needed ? 

@Brandstetter @mattibf will take care of that "dirty-work" =).

**Comment by kornicameister** [comment]
@Brandstetter @mattibf we have #147  but it is full of merge-conflicts so I guess we could as well as drop that if we cut **stable/ocata**. Once we do it, we can simply create new PR and set the base to **stable/ocata** of [this](https://github.com/monasca/monasca-docker) repository.

In the meantime, @timothyb89 do you think it would make sense to remove all of the entries from each module's build.yml leaving only those that refer to latest versions of monasca-docker ?

**Comment by kornicameister** [comment]
@timothyb89 friendly reminder

an update: not **stable/ocata** but **stable/pike**

**Comment by witekest** [comment]
I have created **stable/pike** branch. Please use it to update configuration and variables to fit upstream **stable/pike**.

**Comment by timothyb89** [comment]
@kornicameister I think that would be a good idea, those entries predate the proper stable branches.
