### ISSUE TITLE
Clarify the current state and roadmap

### ISSUE THREAD

**Issue by timothyb89** [monasca/monasca-docker#42]
We need to improve how we communicate the state of the project. Right now we aren't ready to declare either monasca-docker or monasca-helm "stable", and that needs to be made more clear.

We should:
- [ ] make the state and goals of this project in the top-level README.md
- [ ] clarify that monasca-docker's docker-compose env is intended for dev use, and that monasca-helm should be used for production
- [ ] keep track of outstanding issues in GitHub issues
- [ ] publish milestones and a roadmap toward a stable release
